# Generated by ChatGPT on 2026-02-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
