# Generated by Django 6.0.1 on 2026-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evidence',
            name='media_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evidence',
            name='witness_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('WITNESS', 'Witness/Statement'), ('MEDICAL', 'Medical/Biological'), ('VEHICLE', 'Vehicle'), ('ID_DOC', 'ID Document')], default='GENERIC', max_length=20),
        ),
    ]
