# Generated by Django 6.0.1 on 2026-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidence_image_urls_evidence_media_urls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='media_urls',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='witness_statement',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('MEDICAL', 'Medical/Biological'), ('VEHICLE', 'Vehicle'), ('ID_DOC', 'ID Document')], default='GENERIC', max_length=20),
        ),
    ]
